name: Auto pull request

on:
  push:
    branches:
      - release-candidate
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: ["Dependabot auto merge"]
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  autopull:
    uses: Kehet/shared-github-workflows/.github/workflows/auto-pull-request.yml@master
