name: Run tests

on:
  push:
  workflow_dispatch:
  workflow_call:
  merge_group:
  workflow_run:
    workflows: ["Auto pull request"]
    types:
      - completed

permissions:
  contents: read

jobs:
  tests:
    uses: Kehet/shared-github-workflows/.github/workflows/js-tests.yml@master
